drop table if exists banner CASCADE;
drop table if exists image CASCADE;
drop table if exists member CASCADE;
drop table if exists notify CASCADE;
drop table if exists product CASCADE;
drop table if exists product_image CASCADE;
drop table if exists product_start_date CASCADE;
drop table if exists review CASCADE;
drop table if exists token CASCADE;
drop table if exists travel_place CASCADE;

create table banner
(
    id         bigint generated by default as identity,
    hashtag    varchar(255),
    image      varchar(255),
    product_id bigint,
    title      varchar(255),
    primary key (id)
);

create table image
(
    image_type varchar(31) not null,
    image_id   bigint generated by default as identity,
    image_key  varchar(255),
    image_url  varchar(255),
    notify_id  bigint,
    review_id  bigint,
    primary key (image_id)
);

create table member
(
    member_id      bigint generated by default as identity,
    created_at     varchar(255),
    modified_at    varchar(255),
    area           varchar(255),
    authority      varchar(255),
    birth          varchar(255),
    email          varchar(255),
    gender         varchar(255),
    group_trip     varchar(255),
    password       varchar(255),
    recommend      varchar(255),
    recommend_code varchar(255),
    tel            varchar(255),
    theme          varchar(255),
    username       varchar(255),
    primary key (member_id)
);

create table notify
(
    d_type      varchar(31)  not null,
    notify_id   bigint generated by default as identity,
    created_at  varchar(255),
    modified_at varchar(255),
    content     varchar(255) not null,
    title       varchar(255) not null,
    notify_type varchar(255),
    sequence    bigint,
    member_id   bigint       not null,
    primary key (notify_id)
);

create table product
(
    product_id  bigint generated by default as identity,
    created_at  varchar(255),
    modified_at varchar(255),
    destination varchar(255),
    packaging   varchar(255),
    price       integer,
    priority    integer,
    summary     varchar(255),
    target      varchar(255),
    theme       varchar(255),
    thumbnail   varchar(255),
    title       varchar(255),
    primary key (product_id)
);

create table product_image
(
    product_image_id bigint generated by default as identity,
    image            varchar(255),
    product_id       bigint,
    primary key (product_image_id)
);

create table review
(
    review_id   bigint generated by default as identity,
    member_id   bigint       not null,
    product_id  bigint,
    title       varchar(255) not null,
    content     varchar(255) not null,
    created_at  varchar(255),
    modified_at varchar(255),
    primary key (review_id)
);

create table product_start_date
(
    product_start_date_id bigint generated by default as identity,
    start_date            integer,
    product_id            bigint,
    primary key (product_start_date_id)
);


create table token
(
    id            varchar(255) not null,
    access_token  varchar(255),
    refresh_token varchar(255),
    primary key (id)
);

create table travel_place
(
    travel_place_id bigint generated by default as identity,
    member_id       bigint,
    product_id      bigint,
    primary key (travel_place_id)
);

alter table image
    add constraint FKqm8u8v0joadns8ta8ddxj8y3w
        foreign key (notify_id)
            references notify;

alter table image
    add constraint FK2fyo6jg4fpq9108cbi16v37ft
        foreign key (review_id)
            references review;

alter table notify
    add constraint FKp28fj4wlylqm634y0f2h1nxbb
        foreign key (member_id)
            references member;

alter table product_image
    add constraint FK6oo0cvcdtb6qmwsga468uuukk
        foreign key (product_id)
            references product;

alter table product_start_date
    add constraint FKsj7gow2r5x7uj8jo7jhauecxy
        foreign key (product_id)
            references product;

alter table review
    add constraint FKk0ccx5i4ci2wd70vegug074w1
        foreign key (member_id)
            references member;

alter table review
    add constraint FKiyof1sindb9qiqr9o8npj8klt
        foreign key (product_id)
            references product;

alter table travel_place
    add constraint FKaf5ylivy6022iuurwxsvcu488
        foreign key (member_id)
            references member;

alter table travel_place
    add constraint FKcfe043jo3lj947a0faf71ibsj
        foreign key (product_id)
            references product;